### ISSUE TITLE
how to test-app on grails-audit-trail  with grails 2.0.3?

### ISSUE THREAD

**Issue by sjbwylbs** [9ci/grails-audit-trail#9]
when i upgrade grails-audit-trail's grails runtime env to 2.0.3,it cause some error.
test-app error --stacktrace is below 
| Running 3 unit tests... 3 of 3
| Failure:  testSomething(nine.tests.TestDomainTests)
|  Assertion failed: 

assert data.metaClass.hasProperty(data,key)
       |    |         |           |    |
       |    |         null        |    createdDate
       |    |                     nine.tests.TestDomain : null
       |    org.codehaus.groovy.runtime.HandleMetaClass@614c97d4[groovy.lang.ExpandoMetaClass@614c97d4[class nine.tests.TestDomain]]
       nine.tests.TestDomain : null

```
at nine.tests.TestDomainTests$_testSomething_closure1.doCall(TestDomainTests.groovy:22)
at nine.tests.TestDomainTests.testSomething(TestDomainTests.groovy:21)
```

| Completed 3 unit tests, 1 failed in 1745ms
| Compiling 4 source files.
| Error Compilation error compiling [integration] tests: startup failed:
/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 5: unable to resolve class org.codehaus.groovy.grails.plugins.springsecurity.GrailsUser
 @ line 5, column 1.
   import org.codehaus.groovy.grails.plugins.springsecurity.GrailsUser
   ^

/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 6: unable to resolve class org.springframework.security.authentication.UsernamePasswordAuthenticationToken
 @ line 6, column 1.
   import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
   ^

/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 7: unable to resolve class org.springframework.security.core.authority.AuthorityUtils
 @ line 7, column 1.
   import org.springframework.security.core.authority.AuthorityUtils
   ^

/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 8: unable to resolve class org.springframework.security.core.context.SecurityContextHolder
 @ line 8, column 1.
   import org.springframework.security.core.context.SecurityContextHolder as SCH
   ^

4 errors
 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 5: unable to resolve class org.codehaus.groovy.grails.plugins.springsecurity.GrailsUser
 @ line 5, column 1.
   import org.codehaus.groovy.grails.plugins.springsecurity.GrailsUser
   ^

/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 6: unable to resolve class org.springframework.security.authentication.UsernamePasswordAuthenticationToken
 @ line 6, column 1.
   import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
   ^

/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 7: unable to resolve class org.springframework.security.core.authority.AuthorityUtils
 @ line 7, column 1.
   import org.springframework.security.core.authority.AuthorityUtils
   ^

/Users/wenhaoliu/gitrepo/grails-audit-trail/test/integration/nine/tests/BaseInt.groovy: 8: unable to resolve class org.springframework.security.core.context.SecurityContextHolder
 @ line 8, column 1.
   import org.springframework.security.core.context.SecurityContextHolder as SCH
   ^

4 errors

```
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.codehaus.gant.GantBuilder.invokeMethod(GantBuilder.java:99)
at _GrailsTest_groovy$_run_closure3.doCall(_GrailsTest_groovy:266)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at _GrailsTest_groovy$_run_closure3.call(_GrailsTest_groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:245)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at java_util_concurrent_Callable$call.call(Unknown Source)
at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at TestApp$_run_closure1.doCall(TestApp.groovy:82)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at java_util_concurrent_Callable$call.call(Unknown Source)
at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at java_util_concurrent_Callable$call.call(Unknown Source)
at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at java_util_concurrent_Callable$call.call(Unknown Source)
at gant.Gant.withBuildListeners(Gant.groovy:427)
at gant.Gant.this$2$withBuildListeners(Gant.groovy)
at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
at gant.Gant.dispatch(Gant.groovy:415)
at gant.Gant.this$2$dispatch(Gant.groovy)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at gant.Gant.invokeMethod(Gant.groovy)
at gant.Gant.executeTargets(Gant.groovy:591)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
at gant.Gant.executeTargets(Gant.groovy:590)
at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1231)
```

| Error Compilation error compiling [integration] tests: startup failed:
